name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create and publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn install
      - name: Check build
        run: yarn build
      - name: Check coding standards
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
